# Generated by Django 4.2.6 on 2023-11-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_content_alter_book_isbn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='public_target',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
